var demo = {
 "name": "demo",
 "template": "Simple",
 "settings":{
	 
 },
 "before": {
  "Process": {
   "Select Request": {
    "type": "SQL",
    "desc": "Select request data based on ID.",
    "code": "select d_request, cd_status, t_descriptionfrom dm.dm_r_requirementwhere cd_record = :I_Req_Code",
    "mapping": "I_Req_Date, S_Status, I_Req_desc"
   }
  },
  "Check": {
   "Check Request Status": {
    "type": "Expression",
    "level": "error",
    "message": "Request is not ready for edit",
    "el": "",
    "desc": "Check, if status is not edit",
    "code": "S_Status != 'edit'"
   },
   "Deadline not specified": {
    "type": "Expression",
    "level": "warning",
    "message": "Deadline is not specified, pleas specify",
    "el": "I_Req_Deadline",
    "desc": "Check, if deadline is specified",
    "code": "I_Req_Deadline == ''"
   }
  }
 },
 "page": {
  "sort": [
   "Top",
   "Center",
   "Bottom"
  ],
  "Top": {
   "col": "",
   "label": "Request for Business Term",
   "small": "N",
   "tooltip": "",
   "margin": "2",
   "bg_color": "light",
   "padding": "2",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "border": "primary",
   "border_radius": "rounded",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "column",
   "flex": "Y",
   "type": "div",
   "sort": [
    "Toolbar",
    "Form_request"
   ],
   "parent": "Start"
  },
  "Center": {
   "col": "",
   "label": "Required Business Terms",
   "small": "N",
   "tooltip": "",
   "margin": "2",
   "bg_color": "",
   "padding": "2",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "border": "secondary",
   "border_radius": "rounded",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "column",
   "flex": "Y",
   "type": "div",
   "sort": [
    "Toolbar_Center",
    "Core_Properties"
   ],
   "parent": "Start"
  },
  "Bottom": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "border": "",
   "border_radius": "",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "B_Advanced"
   ],
   "parent": "Start"
  },
  "Toolbar": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "1",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "border": "primary",
   "border_radius": "rounded",
   "template": "btn-group",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "grow",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "Button_Group"
   ],
   "parent": "Top"
  },
  "B_Create": {
   "label": "Create",
   "col": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "show_if": "",
   "show_if_txt": "",
   "read_if": "",
   "read_if_txt": "",
   "permission": "",
   "color": "primary",
   "size": "",
   "goto_page": "Create Request",
   "mapping": [
    [
     "I_Rec_Code",
     "I_Rec_Code"
    ]
   ],
   "type": "button",
   "parent": "Button_Group"
  },
  "B_Delete": {
   "col": "",
   "label": "Delete",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Button_Group"
  },
  "B_Find": {
   "col": "",
   "label": "Find",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Button_Group"
  },
  "B_Save": {
   "col": "",
   "label": "Save",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Button_Group"
  },
  "B_Back": {
   "col": "",
   "label": "Back",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Button_Group"
  },
  "Form_request": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "1",
   "bg_color": "",
   "padding": "2",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "border": "primary",
   "border_radius": "rounded",
   "template": "form-group",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "First",
    "Second",
    "Third"
   ],
   "parent": "Top"
  },
  "I_Req_Code": {
   "col": "",
   "label": "Requirement Code",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "class": "",
   "subtype": "text",
   "placeholder": "BD19.04.01",
   "type": "input text",
   "parent": "First"
  },
  "I_Req_Deadline": {
   "col": "",
   "label": "Requirement Deadline",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "class": "",
   "subtype": "text",
   "placeholder": "",
   "type": "input text",
   "parent": "First"
  },
  "Button_Group": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "50",
   "flex_height": "",
   "class": "",
   "border": "",
   "border_radius": "",
   "template": "btn-group",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "B_Create",
    "B_Delete",
    "B_Find",
    "B_Save",
    "B_Back"
   ],
   "parent": "Toolbar"
  },
  "I_Origin": {
   "col": "",
   "label": "Originated by",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "class": "",
   "subtype": "text",
   "placeholder": "",
   "type": "input text",
   "parent": "First"
  },
  "First": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "25",
   "flex_height": "",
   "class": "",
   "border": "",
   "border_radius": "",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "column",
   "flex": "Y",
   "type": "div",
   "sort": [
    "I_Req_Code",
    "I_Req_Deadline",
    "I_Origin"
   ],
   "parent": "Form_request"
  },
  "Second": {
   "label": "",
   "col": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "50",
   "flex_height": "",
   "class": "",
   "show_if": "",
   "show_if_txt": "",
   "read_if": "",
   "read_if_txt": "",
   "permission": "",
   "border": "",
   "border_radius": "",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "column",
   "flex": "Y",
   "type": "div",
   "sort": [
    "Req_Second_Top",
    "I_Req_desc"
   ],
   "parent": "Form_request"
  },
  "S_Status": {
   "col": "",
   "label": "Requirement Status",
   "small": "N",
   "tooltip": "",
   "margin": "0",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "subtype": "list",
   "value": "new,approved,done",
   "type": "input select",
   "parent": "Req_Second_Top"
  },
  "I_Req_Date": {
   "col": "",
   "label": "Requirement Date",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "class": "",
   "subtype": "text",
   "placeholder": "2019.04.25",
   "type": "input text",
   "parent": "Req_Second_Top"
  },
  "I_Requestor": {
   "col": "",
   "label": "Requestor",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "class": "",
   "subtype": "text",
   "placeholder": "J.Doe",
   "type": "input text",
   "parent": "Req_Second_Top"
  },
  "Toolbar_Center": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "1",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "border": "secondary",
   "border_radius": "rounded",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "Button_Group_2"
   ],
   "parent": "Center"
  },
  "Button_Group_2": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "50",
   "flex_height": "",
   "class": "",
   "border": "",
   "border_radius": "",
   "template": "btn-group",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "B_Prev",
    "B_Next",
    "B_Create_2",
    "B_Delete_2"
   ],
   "parent": "Toolbar_Center"
  },
  "B_Prev": {
   "col": "",
   "label": "Previous",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Button_Group_2"
  },
  "B_Next": {
   "col": "",
   "label": "Next",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Button_Group_2"
  },
  "B_Create_2": {
   "col": "",
   "label": "Create",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Button_Group_2"
  },
  "B_Delete_2": {
   "col": "",
   "label": "Delete",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Button_Group_2"
  },
  "Core_Properties": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "border": "",
   "border_radius": "",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "Core_Properties_Left",
    "Core_Properties_Right"
   ],
   "parent": "Center"
  },
  "Core_Properties_Left": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "25",
   "flex_height": "",
   "class": "",
   "border": "",
   "border_radius": "",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "column",
   "flex": "Y",
   "type": "div",
   "sort": [
    "i_Req_Operation",
    "I_term_status",
    "I_Name_En",
    "I_Name_SK",
    "B_Search_Exist"
   ],
   "parent": "Core_Properties"
  },
  "i_Req_Operation": {
   "col": "",
   "label": "Requested Operation",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "subtype": "list",
   "value": "create,in progress, closed",
   "type": "input select",
   "parent": "Core_Properties_Left"
  },
  "I_term_status": {
   "col": "",
   "label": "Term Status",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "subtype": "list",
   "value": "draft,in production",
   "type": "input select",
   "parent": "Core_Properties_Left"
  },
  "I_Name_En": {
   "col": "",
   "label": "Name En",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "subtype": "text",
   "placeholder": "",
   "type": "input text",
   "parent": "Core_Properties_Left"
  },
  "I_Name_SK": {
   "col": "",
   "label": "Name SK",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "subtype": "text",
   "placeholder": "",
   "type": "input text",
   "parent": "Core_Properties_Left"
  },
  "B_Search_Exist": {
   "col": "",
   "label": "Search Existing",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Core_Properties_Left"
  },
  "Core_Properties_Right": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "2",
   "bg_color": "",
   "padding": "",
   "flex_width": "75",
   "flex_height": "",
   "class": "",
   "border": "",
   "border_radius": "",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "column",
   "flex": "Y",
   "type": "div",
   "sort": [
    "I_Req_Oper_Descr",
    "I_Desc_EN",
    "I_Desc_SK",
    "I_Example"
   ],
   "parent": "Core_Properties"
  },
  "I_Req_desc": {
   "col": "",
   "label": "Request Description",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "100",
   "flex_height": "",
   "class": "",
   "rows": "6",
   "type": "input textarea",
   "parent": "Second"
  },
  "Req_Second_Top": {
   "col": "",
   "label": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "border": "",
   "border_radius": "",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "S_Status",
    "I_Req_Date",
    "I_Requestor"
   ],
   "parent": "Second"
  },
  "I_Req_Oper_Descr": {
   "col": "",
   "label": "Requested Operation Description",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "100",
   "flex_height": "",
   "class": "",
   "rows": "4",
   "type": "input textarea",
   "parent": "Core_Properties_Right"
  },
  "I_Desc_EN": {
   "col": "",
   "label": "Description EN",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "subtype": "text",
   "placeholder": "",
   "type": "input text",
   "parent": "Core_Properties_Right"
  },
  "I_Desc_SK": {
   "col": "",
   "label": "Description SK",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "subtype": "text",
   "placeholder": "",
   "type": "input text",
   "parent": "Core_Properties_Right"
  },
  "I_Example": {
   "col": "",
   "label": "Example Values",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "1",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "subtype": "text",
   "placeholder": "",
   "type": "input text",
   "parent": "Core_Properties_Right"
  },
  "B_Advanced": {
   "col": "",
   "label": "Advanced Properties",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "",
   "flex_height": "",
   "class": "",
   "color": "primary",
   "size": "",
   "type": "button",
   "parent": "Bottom"
  },
  "Third": {
   "label": "",
   "col": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "",
   "flex_width": "50",
   "flex_height": "",
   "class": "",
   "show_if": "",
   "show_if_txt": "",
   "read_if": "",
   "read_if_txt": "",
   "permission": "",
   "border": "primary",
   "border_radius": "rounded",
   "template": "",
   "flex_align_items": "",
   "flex_align_self": "",
   "flex_justify_content": "",
   "flex_grow": "",
   "flex_direction": "",
   "flex": "Y",
   "type": "div",
   "sort": [
    "T_History"
   ],
   "parent": "Form_request"
  },
  "T_History": {
   "label": "History",
   "col": "",
   "small": "N",
   "tooltip": "",
   "margin": "",
   "bg_color": "",
   "padding": "2",
   "flex_width": "100",
   "flex_height": "",
   "class": "",
   "show_if": "",
   "show_if_txt": "",
   "read_if": "",
   "read_if_txt": "",
   "permission": "",
   "color": "primary",
   "columns": [
    [
     "t_user_name",
     "User Name",
     ""
    ],
    [
     "d_date",
     "Date",
     ""
    ],
    [
     "t_desc",
     "Description",
     ""
    ]
   ],
   "SQL": "select t_user_name, d_date, t_desc from requests_history where cd_code = :i_req_code",
   "type": "table",
   "parent": "Third"
  }
 },
 "after": {
  "Check": {},
  "Process": {
   "Update Requirement": {
    "type": "SQL",
    "btn": "B_Save",
    "desc": "Update requirement data",
    "code": "update dm.dm_r_requirementset d_request = :I_Req_Date, cd_status = :S_Status, d_deadline = :I_Req_Deadlinewhere cd_record = :I_Req_Code",
    "mapping": "I_Req_date, S_Status, I_Req_Deadline,I_Req_Code"
   }
  }
 }
};