theme: jekyll-theme-cayman
title: Raspberry UI Framework
description: "Raspberry is low-code/configuration framework for creating responsive web frontend for common database systems using Bootstrap CSS templates. Raspberry is focused on developers with database background with basic knowledge of FE technologies like Bootstrap and JQuery/Javascript.

Raspberry is licensed under the GPL"
